# Generated by Django 3.0.8 on 2020-07-11 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_username', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                (
                'account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='from_account',
                                                   to='mock_banking.Account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='to_account',
                                                 to='mock_banking.Account')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
