# Generated by Django 3.0.8 on 2020-07-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mock_banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
    ]
